import Link from "next/link";
import { CancelBooking } from "@/components/cancel-booking";
import { listUpcomingBookings } from "@/lib/data/bookings";
import { listRooms } from "@/lib/data/rooms";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ room?: string }> }) {
  const { room } = await searchParams;
  const [rooms, bookings] = await Promise.all([listRooms(), listUpcomingBookings(room)]);
  const confirmed = bookings.filter((booking) => booking.status === "confirmed").length;
  return <main className="app-shell executive-shell"><header className="app-header"><div className="brand-block"><p className="eyebrow"><i /> MEETING ROOMS</p><p className="location">Corporate workspace · Operations console</p></div><nav aria-label="Primary navigation"><Link href="/">Availability</Link><Link className="active" href="/admin">Admin console</Link></nav></header><section className="hero"><div><p className="eyebrow"><i /> RESERVATION OPERATIONS</p><h1>Reservations admin</h1><p className="subtitle">Review the team&apos;s upcoming room schedule and release spaces when plans change.</p></div><div className="hero-status"><span className="pulse" /> {confirmed} active</div></section><section className="date-bar"><div><span>Upcoming reservations</span><strong>{bookings.length} records</strong></div><form><select aria-label="Filter reservations by room" name="room" defaultValue={room ?? ""}><option value="">All rooms</option>{rooms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="secondary">Filter</button></form></section><section className="panel admin-panel"><div className="panel-heading"><div><p className="eyebrow">TEAM SCHEDULE</p><h2>Reservations</h2></div><span className="count-chip">{confirmed} confirmed</span></div>{bookings.length === 0 ? <p className="muted">No upcoming reservations match this filter.</p> : <div className="reservation-table"><div className="table-head"><span>Date & time</span><span>Room</span><span>Meeting</span><span>Status</span><span>Action</span></div>{bookings.map((booking) => <div className="table-row" key={booking.id}><span data-label="Date & time">{booking.booking_date}<small>{booking.start_time.slice(0, 5)}–{booking.end_time.slice(0, 5)}</small></span><span data-label="Room">{booking.rooms?.name ?? "Unknown room"}<small>{booking.rooms?.location}</small></span><span data-label="Meeting"><strong>{booking.title}</strong><small>{booking.organiser}{booking.attendees ? ` · ${booking.attendees}` : ""}</small></span><span data-label="Status" className={`status ${booking.status}`}>{booking.status}</span><span data-label="Action">{booking.status === "confirmed" ? <CancelBooking bookingId={booking.id} /> : <small>{booking.cancellation_reason}</small>}</span></div>)}</div>}</section><nav className="mobile-nav" aria-label="Mobile navigation"><Link href="/">Availability</Link><Link className="active" href="/admin">Admin</Link></nav></main>;
}
